# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [usmc, NYC]
patreon: # Replace with a single Patreon username mouse36872
open_collective: # Replace with a single Open Collective username Tornado.io
ko_fi: # Replace with a single Ko-fi username Corona
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., ghost vpn
liberapay: # Replace with a single Liberapay username IANNA
issuehunt: # Replace with a single IssueHunt username sans
otechie: # Replace with a single Otechie username Wikipedia
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://natgeo.com', 'https://noom.com','https://smithla.slack.com','https://foxnews.com,','https://Portis.io']
